### ISSUE TITLE
Error in memory and problem to porting

### ISSUE THREAD

**Issue by hiperiondev** [kalamara/librelogic#4]
I see that you have taken up the project. Congratulations!
I am making a port to ESP32 and I have found some problems.
I'll be adding fixes as I find issues.
I have added -fsanitize=address to tests and there are a LOT of memory leaks

https://github.com/kalamara/librelogic/pull/3

**Comment by hiperiondev** [comment]
This is all for now. If proposed commits are merged I'll continue with some changes for improve port to microcontrollers

**Comment by hiperiondev** [comment]
From Valgrind there are a lot of memory errors

https://pastebin.com/bBaVBwNa

**Comment by kalamara** [comment]
Thank you for your contribution! I have been meaning to look into some of these fixes. I will try to fix as many of the valgrind errors as i can, and make a bugfixing release in the christmas holidays :) 
Specifically about style changes: i have been looking into using a tool to apply style automatically. so far i am in favor of https://astyle.sourceforge.net/
What tool did you use?
Please note, the code style will be revisited once we have doxygen in place.

**Comment by kalamara** [comment]
AFAIK ESP32 supports micropython so you might be able to benefit from the Python CFFI interface that is added now :)

**Comment by hiperiondev** [comment]
To program I use Eclipse. This allows you to define styles that can be easily applied to code.
On ESPS32 I use native ESP-IDF, micropython is quite slow

**Comment by hiperiondev** [comment]
I never used https://astyle.sourceforge.net/ but I assume it will do the same as the Eclipse function.
I think the use of Doxygen is an excellent idea. Also Sphynx is a very good documentation tool.
I recently created the documentation (and Spanish translation) for another project (https://github.com/berry-lang/berry) and this is the result: https://berry-temp.readthedocs.io/

**Comment by hiperiondev** [comment]
On the other hand, BYTE and BIT are defined in data.h, but these macros already exist in some microcontroller frameworks. They should have another name so they don't get overwritten. Is it okay to rename them as _BYTE and _BIT?

**Comment by kalamara** [comment]
> On the other hand, BYTE and BIT are defined in data.h, but these macros already exist in some microcontroller frameworks. They should have another name so they don't get overwritten. Is it okay to rename them as _BYTE and _BIT?

sure no problem. maybe better PLC_BYTE and PLC_BIT as you did with the error codes

**Comment by hiperiondev** [comment]
> sure no problem. maybe better PLC_BYTE and PLC_BIT as you did with the error codes

Ok, I'll use PLC_

**Comment by hiperiondev** [comment]
https://github.com/kalamara/librelogic/pull/5

**Comment by hiperiondev** [comment]
In the second commit you can find a simple change that I've made to simplify external new hardware definition.
This allow to add a new HW without touch the code (good for add libreligic as git subproject)

**Comment by hiperiondev** [comment]
You can see how I've used this in: https://github.com/hiperiondev/librelogic-esp32/tree/main/components/librelogic

**Comment by hiperiondev** [comment]
I'll will rethink external hardware method
