### ISSUE TITLE
External hardware definition

### ISSUE THREAD

**Issue by hiperiondev** [kalamara/librelogic#7]
I have change the new hardware definition maintaining the actual structure.
You can see the little change before create a push request: https://github.com/hiperiondev/librelogic

**Comment by kalamara** [comment]
i think i must have merged that one as part of the BYTE / BIT rename pull request

**Comment by hiperiondev** [comment]
Maybe, not a big issue.
Are you agree with changes? If are ok I'll make a pull request

**Comment by kalamara** [comment]
please make a pull request to make sure what the changes are.

**Comment by hiperiondev** [comment]
This has been merged at :
Add external hardware definition for new ports
    commit 1c3ca82c342970df91756831e27c98eda10319d0
